### ISSUE TITLE
apps not showing good with dark theme

### ISSUE THREAD

**Issue by kapcom01** [Chais/nextcloud-themes#1]
Hello,

Apps like calendar, contacts, notes, announcements, markdown editor, are not showing good. I am not sure if this has to do with the theme or the apps, but I thought I should open an issue here first.

Thanks.

![2017-02-08 19-11-10](https://cloud.githubusercontent.com/assets/21684/22748412/adbae3b4-ee32-11e6-8621-e965d3cbfdb3.png)

**Comment by Chais** [comment]
I know. But I don't know enough CSS to quickly fix it and currently don't have the time to dive into it. If you can fix it or know someone who does, I gladly accept pull requests.
