### ISSUE TITLE
Themes broken on Nextcloud 12.0.0

### ISSUE THREAD

**Issue by QBFreak** [Chais/nextcloud-themes#2]
These themes don't work out of the box on Nextcloud 12.0.0. My solution, [found here](https://github.com/nextcloud/server/issues/5036#issuecomment-303357862), was to copy `material-dark/core/css/styles.css` to `material-dark/core/css/server.css`

Awesome dark theme! Too much of the internet is too bright :)

**Comment by Chais** [comment]
How I love undocumented changes… I also prefer dark themes. Sadly it does't properly work with most apps.
